#ifndef _STATUS_CODES_H_
#define _STATUS_CODES_H_

typedef enum
{
    SUCCESS,
    FAILURE,
    TOO_FEW_ARGS,
    TOO_MANY_ARGS,
    INVALID_ARGS,
    CANT_OPEN_FILE,
    CANT_READ_ITEMS,
    CANT_PROCESS_ITEMS,
    MAX_ITEMS_AMOUT_REACHED,
    MAX_ITEM_NAME_SIZE_REACHED,
    INVALID_ITEM_NAME,
    INVALID_ITEM_VOLUME,
    INVALID_ITEM,
    END_OF_FILE_REACHED
} status_code_t;

#endif // _STATUS_CODES_H_
